# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.2.60.dev148+g196084a.d20220501'
version_tuple = (0, 2, 60, 'dev148', 'g196084a.d20220501')
