# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    dependencies = [
        ('edc_appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltimepointstatus',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='TimePointStatus',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='hostname_created',
            field=models.CharField(default='ckgathi', editable=False, help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='id',
            field=edc_base.model.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='HistoricalTimePointStatus',
        ),
    ]
